config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :admins,
    path: 'admins',
    only: [:sessions, :registrations],
    controllers: {
      sessions: 'admins/sessions',
      registrations: 'admins/registrations'
    }

  namespace :admins, path: 'admins' do
    resources :flights
  end

  namespace :api do
    namespace :v1 do
      resources :flights, only: [:show, :index] do
        resources :reservations, only: [:destroy, :create, :index]
      end
    end
  end

  resources :flights, only: :index do
    resources :reservations, only: :index
  end

  root 'flights#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :reservations, dependent: :destroy

  def self.hours_minutes(time)
    hours = time / 60
    minutes = (time) % 60

    "#{ hours }h #{ minutes }min"
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flight

  validates :number, uniqueness: { scope: :flight_id }
  validate :validate_number_of_seats

  private

  def validate_number_of_seats
    return unless flight
    return if flight.number_of_seats > flight.reservations.count

    errors.add(:number_of_seats, 'została przekroczona')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/application_controller.rb
module Admins
  class ApplicationController < ActionController::Base
    before_action :authenticate_admin!

    layout 'admin_application'

  end
end

app/controllers/admins/flights_controller.rb
module Admins
  class FlightsController < Admins::ApplicationController
    before_action :set_flight, only: %i[ show edit update destroy ]

    # GET /flights or /flights.json
    def index
      @flights = Flight.all
    end

    # GET /flights/1 or /flights/1.json
    def show
    end

    # GET /flights/new
    def new
      @flight = Flight.new
    end

    # GET /flights/1/edit
    def edit
    end

    # POST /flights or /flights.json
    def create
      @flight = Flight.new(flight_params)

      if @flight.save
        redirect_to admins_flights_path, notice: "Flight was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /flights/1 or /flights/1.json
    def update
      if @flight.update(flight_params)
        redirect_to admins_flights_path, notice: "Flight was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /flights/1 or /flights/1.json
    def destroy
      @flight.destroy

      redirect_to admins_flights_url, notice: "Flight was successfully destroyed."
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_flight
        @flight = Flight.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def flight_params
        params.require(:flight).permit(:departure_date, :time, :departure, :arrival, :flight_length, :number_of_seats)
      end
  end
end

app/controllers/admins/registrations_controller.rb
module Admins
  class RegistrationsController < Devise::RegistrationsController
    layout 'admin_application'

    def after_sign_up_path_for(resource)
      admins_flights_path
    end
  end
end

app/controllers/admins/sessions_controller.rb
module Admins
  class SessionsController < Devise::SessionsController
    layout 'admin_application'

    def after_sign_in_path_for(resource)
      admins_flights_path
    end
  end
end

app/controllers/api/v1/flights_controller.rb
class Api::V1::FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show ]

  def index
    @flights = Flight.all
    render json: @flights
  end

  def show
    render json: @flight
  end

  private

  def set_flight
    @flight = Flight.find(params[:id])
  end
end

app/controllers/api/v1/reservations_controller.rb
class Api::V1::ReservationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  # GET /flights or /flights.json
  def index
    render json: reservations
  end

  # POST /flights or /flights.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.flight = flight

    if @reservation.save
      render json: @reservation
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end

  def destroy
    reservation.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def reservations
      @reservations ||= flight.reservations
    end

    def flight
      @flight ||= Flight.find(params[:flight_id])
    end

    def reservation
      @reservation ||= reservations.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:number)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    flights_path
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.includes(:reservations).all.map do |flight|
      flight.as_json(include: :reservations)
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = flight.reservations
  end

  private

  def flight
    @flight ||= Flight.find(params[:flight_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/flights/_form.html.erb
<%= form_with(model: @flight, url: admins_flights_path, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.date_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.text_field :departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.text_field :arrival %>
  </div>

  <div class="field">
    <%= form.label :flight_length %>
    <%= form.text_field :flight_length %>
  </div>

  <div class="field">
    <%= form.label :number_of_seats %>
    <%= form.number_field :number_of_seats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= form_with(model: @flight, url: admins_flight_path(id: @flight.id), method: :put, local: true) do |form| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% @flight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.date_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.text_field :departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.text_field :arrival %>
  </div>

  <div class="field">
    <%= form.label :flight_length %>
    <%= form.text_field :flight_length %>
  </div>

  <div class="field">
    <%= form.label :number_of_seats %>
    <%= form.number_field :number_of_seats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', admins_flight_path(id: @flight.id) %> |
<%= link_to 'Back', admins_flights_path %>

app/views/admins/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Departure date</th>
      <th>Time</th>
      <th>Departure</th>
      <th>Arrival</th>
      <th>Flight length</th>
      <th>Number of seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.departure_date %></td>
        <td><%= Flight.hours_minutes(flight.time) %></td>
        <td><%= flight.departure %></td>
        <td><%= flight.arrival %></td>
        <td><%= Flight.hours_minutes(flight.flight_length) %></td>
        <td><%= flight.number_of_seats %></td>
        <td><%= link_to 'Show', admins_flight_path(id: flight.id) %></td>
        <td><%= link_to 'Edit', edit_admins_flight_path(id: flight.id) %></td>
        <td><%= link_to 'Destroy', admins_flight_path(id: flight.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_admins_flight_path %>

app/views/admins/flights/new.html.erb
<h1>New Flight</h1>

<%= form_with(model: @flight, url: admins_flights_path, local: true) do |form| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% @flight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.date_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.text_field :departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.text_field :arrival %>
  </div>

  <div class="field">
    <%= form.label :flight_length %>
    <%= form.text_field :flight_length %>
  </div>

  <div class="field">
    <%= form.label :number_of_seats %>
    <%= form.number_field :number_of_seats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', admins_flights_path %>

app/views/admins/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departure date:</strong>
  <%= @flight.departure_date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @flight.time %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @flight.arrival %>
</p>

<p>
  <strong>Flight length:</strong>
  <%= @flight.flight_length %>
</p>

<p>
  <strong>Number of seats:</strong>
  <%= @flight.number_of_seats %>
</p>

<%= link_to 'Edit', edit_admins_flight_path(id: @flight.id) %> |
<%= link_to 'Back', admins_flights_path %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_admin_session_path %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_admin_registration_path %><br />
<% end %>

app/views/flights/index.html.erb
<%= react_component('ListFlights', { flights: @flights, current_user: current_user }) %>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panel Administracyjny - MobileShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Panel administracyjny</h1>

    <% unless admin_signed_in? %>
      <%= link_to "Log in", new_admin_session_path %><br />
      <%= link_to "Sign up", new_admin_registration_path %><br />
    <% else %>
      <%= link_to "Log out", destroy_admin_session_path, method: 'delete' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <% unless user_signed_in? %>
      <%= link_to "Log in", new_user_session_path %><br />
      <%= link_to "Sign up", new_user_registration_path %><br />
    <% else %>
      <%= link_to "Log out", destroy_user_session_path, method: 'delete' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<%= react_component('Reservation', { flight: @flight, reservations: @reservations }) %>